kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nwp-forecasts
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-2296f927
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwp-forecasts
  annotations: {}
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  volumeName: nwp-forecasts
  resources:
    requests:
      storage: 20Gi
