apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sfa-api
    what: jobscheduler
  name: job-scheduler
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sfa-api
      what: jobscheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sfa-api
        what: jobscheduler
    spec:
      containers:
      - command:
          - /opt/app-root/bin/sfa-api
          - scheduler
          - /conf/job-config.py
        image: quay.io/solararbiter/solarforecastarbiter-api:latest
        name: jobscheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: job-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
      volumes:
      - name: job-config
        secret:
          defaultMode: 420
          secretName: sfa-api-job-config
