apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sfa-api
    what: jobworker
  name: job-worker
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sfa-api
      what: jobworker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sfa-api
        what: jobworker
    spec:
      containers:
      - command:
          - /opt/app-root/bin/sfa-api
          - scheduled-worker
          - --job-monitoring-interval
          - "600"
          - --worker-ttl
          - "720"
          - /conf/job-config.py
        env:
        - name: HOME
          value: /opt/app-root/
        image: quay.io/solararbiter/solarforecastarbiter-api:latest
        name: jobworker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: job-config
        - mountPath: /data
          name: data
        - mountPath: /opt/app-root/.plotly
          name: orca-config
      dnsPolicy: ClusterFirst
      securityContext: {}
      terminationGracePeriodSeconds: 120
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nwp-forecasts
      - name: job-config
        secret:
          defaultMode: 420
          secretName: sfa-api-job-config
      - name: orca-config
        configMap:
          name: orca-config
