apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fetch-nwp
  name: fetch-nwp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fetch-nwp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fetch-nwp
    spec:
      containers:
      - image: quay.io/solararbiter/solarforecastarbiter-core:latest
        imagePullPolicy: Always
        name: fetch-nwp
        env:
          - name: HDF5_USE_FILE_LOCKING
            value: 'FALSE'
        command:
          - sh
          - -c
          - "solararbiter fetchnwp -v /data $(NWP_NAME)"
        resources:
          limits:
            memory: 5Gi
          requests:
            cpu: 100m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: forecasts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: forecasts
        persistentVolumeClaim:
          claimName: nwp-forecasts
