apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

vars:
  - name: NWP_NAME
    objref:
      kind: Deployment
      name: fetch-nwp
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.labels.model
