apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-data
spec:
  schedule: '30 1 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-data
              env:
                - name: NETWORK
                  value: "NOAA SURFRAD"
