apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: redis
  name: redis
data:
  redis-cnf: |
    port 6379
    bind 0.0.0.0
    protected-mode yes
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no

    dir /data
    appendonly yes

    maxmemory 1gb
    maxmemory-policy noeviction
