apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  labels:
    app: redis
  name: redis-auth
spec:
  backendType: systemManager
  data:
    - key: /externalsecrets/redis_auth
      name: redis-auth
