apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sfa-api

resources:
- mysql-secret.yaml
- api-secret.yaml
- redis-secret.yaml
- orca-cm.yaml
- orca-deployment.yaml
- orca-service.yaml
- worker.yaml
- deployment.yaml
- service.yaml
- jobs/job-config.yaml
- jobs/scheduler-deployment.yaml
- jobs/worker-deployment.yaml
