apiVersion: v1
kind: Service
metadata:
  labels:
    app: sfa-api
  name: orca
spec:
  ports:
  - name: 9091-tcp
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    what: orca
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
