apiVersion: v1
kind: Service
metadata:
  labels:
    app: sfa-api
  name: sfa-api
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: sfa-api
    what: mainapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
